parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\State\AppProvider:
        bind:
            $collectionProvider: '@api_platform.doctrine.orm.state.collection_provider'
            $itemProvider: '@api_platform.doctrine.orm.state.item_provider'

    App\Event\AuthenticationListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }
