parameters:
    filesystem:
        basePath: '%kernel.project_dir%/storage/filesystem'
    tempfile:
        basePath: '%kernel.project_dir%/storage/tempfile'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\State\AppProvider:
        bind:
            $collectionProvider: '@api_platform.doctrine.orm.state.collection_provider'
            $itemProvider: '@api_platform.doctrine.orm.state.item_provider'

    App\State\FilesystemProvider:
        bind:
            $itemProvider: '@api_platform.doctrine.orm.state.item_provider'

    App\Event\AuthenticationListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }

    App\Event\FilesystemAutomation:
        tags:
            -   name: 'doctrine.orm.entity_listener'
                event: 'postPersist'
                entity: 'App\Entity\Filesystem'
